name: Deploy Blazor WASM to GitHub Page

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Setup .Net SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        
    

    - name: Publish application
      run: dotnet publish -c Release -o release --nologo
      
    #- name: Change base-tag in index.html
    #  run: sed -i 's/<base href="\/"\/>/<base href="\/simple-ifcjs-blazor\/" \/>/g' release/wwwroot/index.html
    
    # base href url value should be changed so that resources like CSS and scripts can load properly. 
    - name: Rewrite base href
      if: success()
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: release/wwwroot/index.html
        base_href: /simple-ifcjs-blazor/
        
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    #- name: Add .nojekyll file
    #  run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    

    - name: Commit to GitHub pages Repo
      if: success()
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: release/wwwroot
        
